#!/usr/bin/env bash

set -e

script_dir_path=$(dirname "$0")

dependencies_source="$script_dir_path/DEPENDENCIES"
repositories_source="$script_dir_path/REPOSITORIES"

sudo -v

# 1. Install required dependencies

echo "º Installing required dependencies..."

echo "~~~~~~~~"

while read -r dependency;
do
    apt-get install -y $dependency
done < <( cat "$dependencies_source" )

echo "~~~~~~~~"

# 2. Add required PPA repositories

echo "º Adding required PPA repositories..."

echo "~~~~~~~~"

while read -r repository;
do
    add-apt-repository $repository
done < <( cat "$repositories_source" )

echo "~~~~~~~~"

# 3. Updating APT sources

echo "º Updating APT sources..."

echo "~~~~~~~~"

apt-get update

echo "~~~~~~~~"

# 4. Install tools

echo "º Installing tools..."

echo "~~~~~~~~"

tools_files=$(find . -type f -name "*.alias")

while read -r file;
do
    bash $file;

    echo "(+) Installed: $file"
done < <( echo "$tools_files" ) 

echo "~~~~~~~~"

echo "º All done! Tools installation has completed."