@startuml dotfiles_flow
start
title How does the framework work?

skinparam {
    BackgroundColor #00000000
}

:Read modules JSON;
:Transfrom JSON to Python models;
:Transform Python models to Bash files;
:Execute Bash files;
end
@enduml
