@startuml framework_flow
start
title How does the framework work?

skinparam {
    BackgroundColor #00000000
}

:Read modules JSON;
:Convert JSON to Python models;
:Convert Python models to Bash files;
:Execute Bash files;
end
@enduml
