import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.7  # Default: 1.0
padding = { x = 12, y = 12 }

[colors]
transparent_background_colors = true

[colors.primary]
background = "#000000"  # Default

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }