import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
# Opacity
opacity = 0.7  # Default: 1.0
padding = { x = 12, y = 12 }

[colors]

transparent_background_colors = true

[colors.primary]
#foreground = "#000000"
background = "#000000"  # Default